### ISSUE TITLE
Add function argument that can modify quantiles of exposure and the profiles

### ISSUE THREAD

**Issue by JAGoodrich** [Goodrich-Lab/BaHZING#1]
Add function arguments for the following code: 

`#Create exposure dataframe
  X <- Object[x]
  X.q <- apply(X, 2, function(v) { cut(v, breaks=quantile(v, probs=c(0, 0.25, 0.5, 0.75, 1)), include.lowest=TRUE, labels=FALSE) })
  P <- ncol(X.q)
  profiles <- rbind(rep(-0.5,P), rep(0.5, P))`

Need options for different quantiles (3, 4, 5, etc), as well as an option to only use standardized exposures. Also, if the exposures are quantiles, the profiles needs to change to rbind(rep(0,P),  @rep(1, P))

**Comment by Hongxuu** [comment]
For the profiles, Is this what you mean?  

if (standardized) {
    profiles <- rbind(rep(0, P), rep(1, P))
  } else {
    profiles <- rbind(rep(-0.5, P), rep(0.5, P))
  }

**Comment by JAGoodrich** [comment]
It would be good to make this more general. I am thinking that you have a "counterfactual_profiles" argument. The default should be  
`counterfactual_profiles = c(-0.5, 0.5)`

Which should then evaluate to: 

`rbind(rep(counterfactual_profiles[1], P), rep(counterfactual_profiles[2], P))`

However, it would be great to also allow the counterfactual_profiles argument to take a 2xP matrix to allow for customization of the counterfactual profiles. To do this, you could create an if statement that if counterfactual_profiles has length 2, you run the rbind command above, but if it is a 2xP matrix, you just use what is provided. It would be good to include an error statement if counterfactual_profiles is anything other than a length 2 vector or a 2xP matrix, there is an error.

**Comment by Hongxuu** [comment]
BaZING_Model function has been updated.
