### ISSUE TITLE
Change all BaZING to BaHZING

### ISSUE THREAD

**Issue by JAGoodrich** [Goodrich-Lab/BaHZING#12]
To maintain consistency, we should change all BaZING to BaHZING (with the H). 

The easiest way to change this will probably be to use the "Find in Files" function and replace all BaZING with BaHZING. This will be a big change (because it will change a lot of files), so could you coordinate with all of us before doing this to make sure that everyones local changes are merged with the main branch and no one is working on anything?

**Comment by Hongxuu** [comment]
Updated
