### ISSUE TITLE
Update BaHZING defualts

### ISSUE THREAD

**Issue by JAGoodrich** [Goodrich-Lab/BaHZING#14]
update defaults to:
`n.adapt=5000, n.burnin=5000, n.sample=5000
`
This may require changing the examples to make sure that they can run in less time

**Comment by Hongxuu** [comment]
n.burnin and n.sample were not in the BaZING_Model function originally. Does it mean we need to add them? If so, for the testing, what is your suggested value for those two parameters?

**Comment by JAGoodrich** [comment]
n.iter.update should be changed to n.burnin, n.iter.coda should be changed to n.sample
